### ISSUE TITLE
CLM Discussion

### ISSUE THREAD

**Issue by SamMousa** [Bengejd/Pantheon_DKP_Addon#25]
Hi Bengejd,

I'm the creator of the event sourcing library that you've included in your source code. 
It'd be great if you used a modern way of including third party code, that way you can benefit from upgrades & improvements to our source code.
Likewise, if you've made improvements to the library code we'd love to see a PR at  https://github.com/sammousa/lua-eventsourcing

It really is a shame that you chose to "unofficial fork" CLM instead of contributing to it, the community could have benefited greatly from your work!

Cheers,

Sam

**Comment by Bengejd** [comment]
@SamMousa Hi sam! I apologize for the confusion, I'm not actually utilizing the CLM event sourcing library at this time. I originally added it to the project to test out its features and found the easiest way to do that was to just pull it from the CLM library that I already had downloaded and adapt it to see how it worked with my use case. 

I have gone through the Libraries that I have previously tested out / utilized in the past and cleaned them up to only include the ones that are actively being used.

As for the "unofficial fork" of CLM, I think there is a misunderstanding. PantheonDKP has been available since March of 2020, so well before CLM was a project. It has gone through many iterations during that time, and while I mimicked some of CLM's Initialization & Project Structure, I made sure to include CLM in the [Markdown/Credits.md](https://github.com/Bengejd/PantheonDKP/blob/release/Markdown/CREDITS.md) file on the repo. I apologize if I overstepped myself while using CLM structure as inspiration, but I assure you that none of CLM's core functionality is present within PDKP.

**Comment by SamMousa** [comment]
No problem! I just see a lot of bad habits in wow add-ons (due to most developers working on them not being actual developers) so I thought I'd make an issue.

Good luck with further development!

**Comment by Bengejd** [comment]
@SamMousa that's for sure, I know that I've made my fair share of mistakes during my time working on this project. I'd be happy to chat sometime and see if we can try help one another out. 

Let me know if that interested you or not! Gotta go though, time for Puppy class lol.

Jordan
